# Generated by Django 4.2.20 on 2025-03-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('competition_type', models.CharField(choices=[('League', 'League'), ('Cup', 'Cup'), ('International', 'International')], max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('season_year', models.IntegerField()),
                ('current_matchday', models.IntegerField(blank=True, null=True)),
                ('number_of_matchdays', models.IntegerField(blank=True, null=True)),
                ('number_of_teams', models.IntegerField(blank=True, null=True)),
                ('number_of_games', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
