# Generated by Django 4.2.20 on 2025-03-13 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('experience_years', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('positions', models.JSONField()),
                ('shirt_number', models.IntegerField(blank=True, null=True)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('goals', models.FloatField(default=0.0)),
                ('assists', models.FloatField(default=0.0)),
                ('expected_goals', models.FloatField(blank=True, null=True)),
                ('expected_assists', models.FloatField(blank=True, null=True)),
                ('shots_attempted', models.FloatField(default=0.0)),
                ('shots_on_target', models.FloatField(default=0.0)),
                ('shot_accuracy', models.FloatField(blank=True, null=True)),
                ('goals_per_shot', models.FloatField(blank=True, null=True)),
                ('goals_per_shot_on_target', models.FloatField(blank=True, null=True)),
                ('shots_from_free_kicks', models.FloatField(default=0.0)),
                ('pass_completion', models.FloatField(blank=True, null=True)),
                ('progressive_passes', models.FloatField(default=0.0)),
                ('passes_into_final_third', models.FloatField(default=0.0)),
                ('passes_into_penalty_area', models.FloatField(default=0.0)),
                ('crosses_into_penalty_area', models.FloatField(default=0.0)),
                ('through_balls', models.FloatField(default=0.0)),
                ('corner_kicks', models.FloatField(default=0.0)),
                ('tackles_attempted', models.FloatField(default=0.0)),
                ('tackles_won', models.FloatField(default=0.0)),
                ('tackles_def_3rd', models.FloatField(default=0.0)),
                ('tackles_mid_3rd', models.FloatField(default=0.0)),
                ('tackles_att_3rd', models.FloatField(default=0.0)),
                ('dribblers_tackled', models.FloatField(default=0.0)),
                ('dribbles_challenged', models.FloatField(default=0.0)),
                ('dribble_success_rate', models.FloatField(blank=True, null=True)),
                ('interceptions', models.FloatField(default=0.0)),
                ('blocks', models.FloatField(default=0.0)),
                ('passes_blocked', models.FloatField(default=0.0)),
                ('clearances', models.FloatField(default=0.0)),
                ('errors_leading_to_goals', models.FloatField(default=0.0)),
                ('touches', models.FloatField(default=0.0)),
                ('touches_def_3rd', models.FloatField(default=0.0)),
                ('touches_mid_3rd', models.FloatField(default=0.0)),
                ('touches_att_3rd', models.FloatField(default=0.0)),
                ('successful_take_ons', models.FloatField(default=0.0)),
                ('take_on_success_rate', models.FloatField(blank=True, null=True)),
                ('carries', models.FloatField(default=0.0)),
                ('progressive_carrying_distance', models.FloatField(default=0.0)),
                ('miscontrols', models.FloatField(default=0.0)),
                ('dispossessions', models.FloatField(default=0.0)),
                ('fouls_committed', models.FloatField(default=0.0)),
                ('fouls_drawn', models.FloatField(default=0.0)),
                ('offsides', models.FloatField(default=0.0)),
                ('aerial_duels_won', models.FloatField(default=0.0)),
                ('aerial_duels_lost', models.FloatField(default=0.0)),
                ('aerial_win_rate', models.FloatField(blank=True, null=True)),
                ('own_goals', models.FloatField(default=0.0)),
                ('penalty_kicks_won', models.FloatField(default=0.0)),
                ('penalty_kicks_conceded', models.FloatField(default=0.0)),
                ('tendencies', models.JSONField(blank=True, null=True)),
                ('trophies', models.JSONField(blank=True, null=True)),
                ('market_value', models.FloatField(blank=True, null=True)),
                ('is_free_agent', models.BooleanField(default=False)),
                ('coaches', models.ManyToManyField(related_name='players', to='players.coach')),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
            ],
        ),
    ]
