# Generated by Django 4.2.20 on 2025-03-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='players', to='players.coach'),
        ),
    ]
